service: serverless-aws-iot

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
    Action:
      - "iot:Connect"
      - "iot:Publish"
      - "iot:Subscribe"
      - "iot:Receive"
      - "iot:GetThingShadow"
      - "iot:UpdateThingShadow"
    Resource: "*"

functions:
  iotPresignedUrl:
    handler: src/iotPresignedUrl.handler
    timeout: 30
    events:
      - http: OPTIONS /iot-presigned-url
      - http:
          method: GET
          path: /iot-presigned-url
    environment:
      IOT_AWS_REGION: '<Your AWS region>'
      IOT_ENDPOINT_HOST: '<Pick from AWS console IoT -> Settings -> Endpoint>'
      IOT_ACCESS_KEY: '<Access key ID from iot-connector>'
      IOT_SECRET_KEY: '<Secret access key from iot-connector>'
  notifyDisconnect:
    handler: src/notifyDisconnect.handler
    timeout: 30
    events:
      - iot:
          sql: "SELECT * FROM 'last-will'"
    environment:
      IOT_AWS_REGION: '<Your AWS region>'
      IOT_ENDPOINT_HOST: '<Pick from AWS console IoT -> Settings -> Endpoint>'
